### ISSUE TITLE
Please create a release for the latest status

### ISSUE THREAD

**Issue by ivuorinen** [erikw/tmux-dark-notify#3]
Hi, and thank you for all your work!

I'm using this repo as a git submodule in my [dotfiles repo](https://github.com/ivuorinen/dotfiles) and [a workflow to keep all submodules up to date](https://github.com/ivuorinen/dotfiles/blob/main/.github/workflows/update-submodules.yml). The only problem with my system is that it pulls the latest tag, not the latest commit as the submodule HEAD.

Could you please tag the latest state as `v0.1.1` or similar?

Thank you!

**Comment by erikw** [comment]
Here you go 😃

https://github.com/erikw/tmux-dark-notify/releases/tag/v0.1.1
